### ISSUE TITLE
ESLint v6 Support

### ISSUE THREAD

**Issue by toshi-toma** [toshi-toma/eslint-config-airbnb-typescript-prettier#15]
eslint v6 has been released.

v6 support released:
- eslint-config-airbnb
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md#1800--2019-08-10
- typescript-eslint
https://github.com/typescript-eslint/typescript-eslint/blob/master/CHANGELOG.md#200-2019-08-13

**Comment by efoken** [comment]
#16

**Comment by toshi-toma** [comment]
Fixes #16

**Comment by toshi-toma** [comment]
I released as v1.3.0
