### ISSUE TITLE
ESLint 7 support

### ISSUE THREAD

**Issue by DanielRamosAcosta** [toshi-toma/eslint-config-airbnb-typescript-prettier#47]
ESLint 7 has been released: https://eslint.org/blog/2020/02/whats-coming-in-eslint-7.0.0

**Comment by toshi-toma** [comment]
@DanielRamosAcosta 

Thank you!! ref: https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/pull/44

We should be compatible with ESLint 7 too before we can merge this one:

- [ ] `eslint-config-arbnb`
  - [ ] [Issue](https://github.com/airbnb/javascript/issues/2223)
  - [ ] Release
- [x] `eslint-plugin-prettier`
  - [x] [PR](https://github.com/prettier/eslint-plugin-prettier/pull/291)
  - [ ] Release
- [ ] `typescript/eslint`
  - [ ] [Issue](https://github.com/typescript-eslint/typescript-eslint/issues/1550)
  - [ ] Release

**Comment by DanielRamosAcosta** [comment]
Very well planned @toshi-toma, great job! 👏

**Comment by RuniBr** [comment]
@toshi-toma `typescript-eslint` [have officially released v3.0.0](https://github.com/typescript-eslint/typescript-eslint/releases/tag/v3.0.0) as of 17 hours ago. I believe that is one more checkbox you can tick :-)

**Comment by toshi-toma** [comment]
@RuniBr 
Thanks!!

**Comment by toshi-toma** [comment]
`eslint-config-airbnb` has released v18.2.0
https://github.com/airbnb/javascript/blob/master/packages/eslint-config-airbnb/CHANGELOG.md#1820--2020-06-18

We can start work. 🎉
https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/issues/47#issuecomment-626751030

**Comment by toshi-toma** [comment]
@DanielRamosAcosta @RuniBr 

`eslint-config-airbnb-typescript-prettier@v3.1.0` to support `ESLint v7` has been released.🚀
https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/blob/master/CHANGELOG.md#310-2020-06-22

**Comment by DanielRamosAcosta** [comment]
Great work! thanks a lot!!
