### ISSUE TITLE
Configuration for rule "import/no-cycle" is invalid

### ISSUE THREAD

**Issue by tairosonloa** [toshi-toma/eslint-config-airbnb-typescript-prettier#49]
When running `eslint --fix "**/*.{ts,tsx}"` in a TypeScript project after upgrading. Before that everything was fine.

```
$ eslint --fix "**/*.{ts,tsx}

Oops! Something went wrong! :(

ESLint: 7.3.0

Error: .eslintrc.js » eslint-config-airbnb-typescript-prettier » eslint-config-airbnb » 
/my_project_path/node_modules/eslint-config-airbnb-base/index.js » 
/my_project_path/node_modules/eslint-config-airbnb-base/rules/imports.js:

        Configuration for rule "import/no-cycle" is invalid:
        Value null should be integer.
```

My `eslintrc.js`:

```js
module.exports = {
  extends: ['airbnb-typescript-prettier'],
  rules: {
    'prettier/prettier': 'warn',
    'import/prefer-default-export': 0,
    'class-methods-use-this': 0,
    'import/no-extraneous-dependencies': 0,
    'react/jsx-props-no-spreading': 0,
  },
  env: {
    jest: true,
  },
}

```

It wasn't failing with versions:
- eslint 7.2.0
- eslint-config-airbnb-typescript-prettier 2.1.1

It started failed after update to:
- eslint 7.3.0
- eslint-config-airbnb-typescript-prettier 2.2.0

**Comment by toshi-toma** [comment]
@tairosonloa 

Thank you for the Report.

It seems ESLint bug :(
https://github.com/airbnb/javascript/issues/2245#issuecomment-646818237

> I'd suggest downgrading to eslint v7.2 for now.

**Comment by toshi-toma** [comment]
Fixed by ESLint 7.3.1 https://github.com/eslint/eslint/pull/13435

**Comment by tairosonloa** [comment]
I confirm it's working now with `eslint 7.3.1` and `eslint-config-airbnb-typescript-prettier 3.1.0`

**Comment by rootlinux2** [comment]
I'm facing this issue
 
![image](https://user-images.githubusercontent.com/24574267/99693804-c1fd7000-2a59-11eb-8870-02f38af4e8d6.png)

I use eslint 7.13.0
![image](https://user-images.githubusercontent.com/24574267/99693666-a09c8400-2a59-11eb-9f91-cda6e17a4dad.png)
