### ISSUE TITLE
This repo should not support React rules

### ISSUE THREAD

**Issue by seahindeniz** [toshi-toma/eslint-config-airbnb-typescript-prettier#63]
Hi

Sorry for the interruption but as I understand by looking at the statements in the README.md doc. and the title of the repo there is nothing states that this library does support React rules. 
However, when I want to use this lib in my project, I get complaints about the `react/static-property-placement` rule, even if I don't have and set up for React on my project. I track the cause to these lines
https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/blob/d8d1fa295180838a6ea06d0960ae5cf9fa1484e6/package.json#L38-L39
https://github.com/toshi-toma/eslint-config-airbnb-typescript-prettier/blob/d8d1fa295180838a6ea06d0960ae5cf9fa1484e6/index.js#L19-L22

Could please remove them from this library and/or create a separate config module to support React. 
New module can be named like `eslint-config-airbnb-typescript-react-prettier`

**Comment by glebbash** [comment]
Also having this warning when linting non react projects:
`Warning: React version was set to "detect" in eslint-plugin-react settings, but the "react" package is not installed. Assuming latest React version for linting.`

**Comment by LumaKernel** [comment]
@datacrafts-io 's this package [eslint-config-airbnb-base-typescript-prettier](https://github.com/datacrafts-io/eslint-config-airbnb-base-typescript-prettier) looks fine 👍 . And in this regard, this repository's package **should** continue to support react.
