### ISSUE TITLE
Unable to resolve dependencies

### ISSUE THREAD

**Issue by ahtasham637** [toshi-toma/eslint-config-airbnb-typescript-prettier#94]
Could not resolve dependency:
npm ERR! peer eslint@"^5.16.0 || ^6.8.0 || ^7.2.0" from eslint-config-airbnb-typescript-prettier@4.2.0
npm ERR! node_modules/eslint-config-airbnb-typescript-prettier
npm ERR!   dev eslint-config-airbnb-typescript-prettier@"*" from the root project

My node version: 17
nm version: 8
eslint version: ^8

**Comment by toshi-toma** [comment]
@ahtasham637 

`eslint-config-airbnb-typescript-prettier` has just supported ESLint v8.

It is released as v5.0.0
https://www.npmjs.com/package/eslint-config-airbnb-typescript-prettier/v/5.0.0
